# fly.toml app configuration file generated for stor-ai-client on 2023-05-07T12:06:10-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stor-ai-client"
primary_region = "ord"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
